### ISSUE TITLE
MAX_CHANNELS set to 2?

### ISSUE THREAD

**Issue by bweis** [beyondscreen/node-rpi-ws281x-native#123]
Is there a reason that the maximum number of channels is only 2?  I haven't tested it with more yet, figured I should ask before I move forward with testing.

Thanks!

**Comment by psy0rz** [comment]
Its inherit to this system, 2 is the max. But we're working on an SMI version that can do 8 or 16 channels parallel.

**Comment by bweis** [comment]
I see.  Perhaps you could help me out.  Is there an avenue for controlling 4 independent light strips from 4 different GPIO pins on the raspberry pi?

I would love to not have to string all 4 of them together... 😅

**Comment by psy0rz** [comment]
Yes, the only way is via something called SMI, i'm working on it currently: 

https://github.com/psy0rz/rpi-ws281x-smi

**Comment by westonmiller** [comment]
> Yes, the only way is via something called SMI, i'm working on it currently:
> 
> https://github.com/psy0rz/rpi-ws281x-smi

I'm trying to add a channel to my Christmas lights setup. Is it possible to just swap out the `node-rpi-ws281x-native` with the smi version?  I'm not seeing much in the readme.

**Comment by psy0rz** [comment]
Nope its not a drop in repacement.

sorry you have to look in the sources to see how to use it for now.

**Comment by westonmiller** [comment]
Ok, Thank you.  Do you know have to convert an RGB ws2812 signal to a ws2811.  I tried just sending it GRB instead, which mostly works, but the blues look more purple.  (This is related to the MAX CHANNEL limitation as I'm having to add a different type of strand to the end of a ws2812b strand)?

**Comment by psy0rz** [comment]
no sorry
