### ISSUE TITLE
I had to do a `npm install nan` for this to work

### ISSUE THREAD

**Issue by mkpazon** [beyondscreen/node-rpi-ws281x-native#46]

**Comment by usefulthink** [comment]
Hm, nan is definitely in the package.json so it should install automatically, did you install from source or via `npm install rpi-ws281x-native`?

**Comment by usefulthink** [comment]
also, the instructions missed the `npm install`-command, added that.

**Comment by mkpazon** [comment]
Yeah, I think it's because of that. Hehe. Thanks!

**Comment by usefulthink** [comment]
You're welcome. Feel free to open more issues if you have questions...
