### ISSUE TITLE
Soundcard conflict on RPi3

### ISSUE THREAD

**Issue by AdyiPool** [beyondscreen/node-rpi-ws281x-native#49]
The file mentioned in the radme wasn't found on my RPi3/Raspbian. This worked for me

Create a kernel module blacklist file that prevents all the sound drivers from loading:
1. `sudo vi /etc/modprobe.d/blacklist-rgb-matrix.conf`
2. add the following lines:

```
blacklist snd_bcm2835
blacklist snd_pcm
blacklist snd_timer
blacklist snd_pcsp
blacklist snd
```
1. Save the file and quit vi
2. `sudo update-initramfs -u`
3. reboot and confirm no `snd` modules are running by executing the command `lsmod`

**Comment by usefulthink** [comment]
Hi @AdyiPool, thanks for this report! That could be a newer raspbian-version handling this differently. Would you mind putting that information into the README and prepare a pull-request?
