### ISSUE TITLE
Could not verify raspberry-pi version

### ISSUE THREAD

**Issue by Stan92** [beyondscreen/node-rpi-ws281x-native#54]
Hi,
Trying to use the rainbow example, I got this message : 
Could not verify raspberry-pi version. If this is wrong and you are running this on a raspberry-pi

My node version is 7.7.4.

Using the cpuInfo object, here is what I get for the hardware section:

Hardware	: BCM2835
Revision	: a02082
.....

**Comment by usefulthink** [comment]
Is that on a raspberry-pi 3? I don't have one so I couldn't add it to the detection-code.

**Comment by usefulthink** [comment]
btw, the relevant code is here: https://github.com/beyondscreen/node-rpi-ws281x-native/blob/master/lib/ws281x-native.js#L37-L46

**Comment by Stan92** [comment]
Yes it is a PI3 
I use another one and it works

**Comment by usefulthink** [comment]
Thanks! I will add it to the detection-code.
