### ISSUE TITLE
Update brightness, without changing color

### ISSUE THREAD

**Issue by bobbysa** [beyondscreen/node-rpi-ws281x-native#62]
I'm completely new to this, so apologies in advance if this is a simple task, but I would like to know how to update just the brightness of my strip, without affecting a solid color that's already been preloaded by another script. If that's not possible, is there any way to detect the state/color the strip is, set the color from that, and then change the brightness.

**Comment by usefulthink** [comment]
So in the current Version (there will be an update soon) the brightness can be changed using `ws281x.setBrightness(value)` with a value from 0 to 255. 
This will call the internal render-function again, so whatever was rendered the last time will be rendered again with adjusted brightness. (see [here](https://github.com/beyondscreen/node-rpi-ws281x-native/blob/master/lib/ws281x-native.js#L179-L187), the `_outputBuffer` being rendered there is whatever the `render()`-function was called with the last time)

I'm not sure what you mean with

>  [...] a solid color that's already been preloaded by another script.

what I wrote before will only work if both setting of the color-values and adjusting the brightness happen from within the same node-process. Doing this across processes (something like `node set-colors.js` and then `node set-brightness.js`) can not work.

>  [...] is there any way to detect the state/color the strip is [...]

No, the whole thing is just "fire and forget".
