### ISSUE TITLE
[rpi-ws281x-native] it looks like you are not running on a raspberry pi

### ISSUE THREAD

**Issue by socalledsound** [beyondscreen/node-rpi-ws281x-native#64]
Hello, I went through the same Adafruit tutorial that you linked to with a single neopixel on a raspberry pi 2 and am able to get a rainbow animation using their python code.  I'd prefer to work in JS so thought I'd try out your library.  Unfortunately when I run sudo node rainbow.js I get:

[rpi-ws281x-native] it looks like you are not running on a raspberry pi so there will be no functionality exposed by this module. For convenience, implementation stubs are provided.

Any ideas why this is happening?  Help appreciated!

**Comment by socalledsound** [comment]
ps: is 'linux' in the pi detection code case senstive?  when I run uname -a I get 

Linux raspberrypi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux

**Comment by b33son** [comment]
Just FYI, this library works on Raspberry Pi Zero W. I've successfully got it working with OPC and OLA.

**Comment by Granjow** [comment]
@socalledsound it checks this:

    if (process.arch !== 'arm' && process.platform !== 'linux')

Do those differ for you?

**Comment by usefulthink** [comment]
There are quite some raspberry-editions that might give false negatives with the current detection-code. The upcoming version will use completely rewritten code for that.

**Comment by paulhayes** [comment]
Hi there, I discovered this problem too, the rpi-version library hasn't been updated in two years! I've added the RpiZeroW cpu to the list of cpu info in the library and performed a pull request. Hopefully the maintainer will merge in the change soon!

https://github.com/ivsgroup/rpi-version/pull/4

**Comment by usefulthink** [comment]
@paulhayes Awesome, that did at least already land on master. Just needs a new version on npm now.
