### ISSUE TITLE
"Failed to open /dev/vcio" Error

### ISSUE THREAD

**Issue by giacomocarrozzo** [beyondscreen/node-rpi-ws281x-native#80]
Hi, tried to run on my device. I have a Raspberry 2 with HASS.IO (resin.io os) and I get this errors:

`Failed to open /dev/vcio, trying old method.
Can't open device file /dev/mailbox-26: Operation not permitted
Error: init(): initialization failed. sorry – no idea why.
at Error (native)
at EventEmitter.ws281x.init (/usr/src/pixel-wall/node_modules/rpi-ws281x-native/lib/ws281x-native.js:136:14)`

Can someone help me?
Thank you very much

**Comment by usefulthink** [comment]
"Operation not permitted" sounds like you are not running it as root. Might that be the reason?
